### PR TITLE
AEGIS-6416 bump torch version

### PR DESCRIPTION
**Pull request by ilektragiassa**

### CODE REVIEW

**Comment by ilektragiassa** [comment]
No matching distribution found for torch<2,>=1.7

**Review by jamienutter — APPROVED** [review]
Code works fine with this major version bump?

**Comment by ilektragiassa** [comment]
> Code works fine with this major version bump?

The error above appeared no matter the way I tried to install the repo (e.g. from Jamf artifactory/installing the asm2vec requirements from local clone/installing it through the macosmalwaresimilarityasm2vec requirements). After the version bump it works fine locally. I will test the code once more.

**Comment by jamienutter** [comment]
> > Code works fine with this major version bump?
> 
> The error above appeared no matter the way I tried to install the repo (e.g. from Jamf artifactory/installing the asm2vec requirements from local clone/installing it through the macosmalwaresimilarityasm2vec requirements). After the version bump it works fine locally. I will test the code once more.

If you've tested then I'm happy - Thanks

**Pull request merged**
